fix: Incorrect MCPSessionManager param.
All of my MCP tools no longer works as I get warning messages like:
```
025-05-14 17:06:01,385 - WARNING - agent.py:98 - Failed to load MCP DatADOG Toolset: MCPSessionManager.__init__() got an unexpected keyword argument 'errlogger'. Did you mean 'errlog'?.
```